name: Python Test CI

# github events
on:
  push:
    branches:
    - main

env: #environment variable so that 'Run tests' pass. This is just to demo tests
  TEST: 'OK'

jobs:
  python-test:
    runs-on: ubuntu-latest 

    steps:
    - name: Check out the code
    # using github action
      uses: actions/checkout@v4

    # another example of using github actions
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    #This example to show how to install from command line 
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Run python app in directory also command line
    - name: Run tests
      run: python tests.py

  # Added two more test to demonstrate how tests can run in parallel.

  integration-test:
    runs-on: ubuntu-latest

    steps:
    - name: Simulate integration test
      run: echo "Run integration test" && sleep 5 && "Integration test pass!!"

  linting:
    runs-on: ubuntu-latest

    steps:
    - name: Simulate linting
      run: echo "Run linting" && sleep 5 && "Linting pass!!"